alter database[D:\USERS\LJY\SOURCE\REPOS\WEBAPPLICATIONFINAL_LJY\APP_DATA\NORTHWIND.MDF] set single_user with rollback immediate
alter database[D:\USERS\LJY\SOURCE\REPOS\WEBAPPLICATIONFINAL_LJY\APP_DATA\NORTHWIND.MDF] collate Chinese_PRC_CI_AS
alter database[D:\USERS\LJY\SOURCE\REPOS\WEBAPPLICATIONFINAL_LJY\APP_DATA\NORTHWIND.MDF] set multi_user